### ISSUE TITLE
InvalidProtocolBufferException (Protocol message contained an invalid tag (zero))

### ISSUE THREAD

**Issue by kinex** [google/tink#413] opened 2020-08-30 09:50 UTC
In my Android app, I see this exception happening on one device:
`Protocol message contained an invalid tag (zero)., com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException`

Related code where the exception happens (Kotlin code from my Flutter plugin):

```kotlin
.
.
.
"encryptString" -> {
    uiScope.launch {
        try {
            var encryptedDataBase64String: String? = null
            withContext(Dispatchers.IO) {
                initializeTink()

                val applicationId = call.argument<String>("applicationId")
                        ?: throw IllegalArgumentException("applicationId")
                val keySetName = call.argument<String>("keySetName")
                        ?: throw IllegalArgumentException("keySetName")
                val dataString = call.argument<String>("data")
                        ?: throw IllegalArgumentException("data")
                val passwordString = call.argument<String>("password")

                val data = dataString.toByteArray(Charsets.UTF_8)

                val password = passwordString!!.toByteArray(Charsets.UTF_8)

                val keySetHandle = getOrGenerateNewKeysetHandle(applicationContext!!, applicationId, keySetName)
                val aead = keySetHandle.getPrimitive(Aead::class.java)

                val encryptedData = aead.encrypt(data, password)

                encryptedDataBase64String = Base64.encodeToString(encryptedData, Base64.DEFAULT)
            }
            result.success(encryptedDataBase64String)
        } catch (e: Exception) {
            Log.e(LOG_TAG, "Exception", e)
            result.error(
                    "Exception",
                    e.localizedMessage ?: e.message ?: "$e", "$e")
        }
    }
}

```

Tink 1.4.0
Device: Huawei P20 / Android 10

This is an user device so I cannot reproduce it myself (I see this from Crashlytics).

**Comment by kraizman** [comment] 2020-09-06 05:55
+1

**Comment by reviewCleevio** [comment] 2020-09-08 12:38
+1
Its also happening to me on devices Xiaomi MI A1,  Xiaomi Redmi Note 7 and Huawei Honor 5X ...all have Android 9

**Comment by Th0MmyS** [comment] 2020-09-08 12:39
+1
Its also happening to me on devices Xiaomi MI A1,  Xiaomi Redmi Note 7 and Huawei Honor 5X ...all have Android 9

**Comment by FundF** [comment] 2020-09-11 06:22
+1

**Comment by mhelder** [comment] 2020-09-11 06:59
+1

This has also been reported on the issue tracker (under androidx.security-crypto), but stack traces show Tink is in fact generating the exception when reading encrypted content.

https://issuetracker.google.com/issues/164901843
https://issuetracker.google.com/issues/168238828
https://issuetracker.google.com/issues/167701944
https://issuetracker.google.com/issues/168238828

So far, I've only seen reports of crashes on Android 9 & 10.

The issue tracker reports are all related to `security-crypto:1.1.0-alpha02`. For me, downgrading to `1.1.0-alpha01' makes the problem go away. There was a change in the Tink dependency between these two versions:

- `1.1.0-alpha01' -> `tink-android:1.4.0-rc2`
- `1.1.0-alpha02' -> `tink-android:1.4.0`

So my conclusion is something broke or regressed between 1.4.0-rc2 and the stable release. Hopefully that helps narrowing down the cause. Meanwhile, if you're experiencing this crash, it may be a consideration to use 1.4.0-rc2 instead.

**Comment by tholenst** [comment] 2020-09-15 12:31
Thanks for the report, and the issuetracker links.

In many of the issuetracker reports, a stacktrace is offered. They look something like this:

> Caused by com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException
> While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length.
> com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom (GeneratedMessageLite.java:1566)
> com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom (GeneratedMessageLite.java:1664)
> com.google.crypto.tink.proto.Keyset.parseFrom (Keyset.java:957)
> com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read (SharedPrefKeysetReader.java:84)
> com.google.crypto.tink.CleartextKeysetHandle.read (CleartextKeysetHandle.java:58)
> com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read (AndroidKeysetManager.java:321)
> com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset (AndroidKeysetManager.java:280)
> com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build (AndroidKeysetManager.java:230)
> androidx.security.crypto.EncryptedSharedPreferences.create (EncryptedSharedPreferences.java:121)

**Comment by tholenst** [comment] 2020-09-15 12:31
Sorry, misclicked and closed. We're investigating.

**Comment by tholenst** [comment] 2020-09-15 12:37
Let's treat this as duplicate of https://issuetracker.google.com/issues/164901843

**Closed by tholenst** 2020-09-15 12:37 UTC

**Comment by tholenst** [comment] 2020-09-18 09:57
See https://issuetracker.google.com/issues/158234058#comment48 for a summary.

**Comment by kinex** [comment] 2020-10-12 14:37
I see also this error message occurring in Nokia 8.3 5G / Android 10 (end-user's device):
`CodedInputStream encountered an embedded string or message which claimed to have negative size`

Is this related to this issue or should I file a new issue?

Reinstalling the app did not help either.  It seems this is not a random exception, it happens always in this user's device.

I already implemented a retry logic for exceptions of type `InvalidKeyException `and `KeyStoreException` as suggested in the linked issue. This new error message has some other type which I don't know yet. But I guess retrying would not help if reinstalling the app did not help either.

**Comment by Splact** [comment] 2021-07-19 15:20
Don't know if this solves the issue for you all, but apparently changing the `fileName` on `EncryptedSharedPreferences.create` call to something different solved the problem to me.

In my case the issue appeared after updating the crypto version from `1.0.0-rc04` to `1.1.0-alpha03` (I had to extend support to Lollipop). So seems that, with the new version, the old sharedPreferences saved on the phone (working as for `1.0.0-rc04` on Android M+ devices) was not readable anymore. Here the idea of changing the filename, so I ignore any existing shared preferences (that's acceptable with the app I'm working on, and it's way better than crash on launch) and start reading/writing on a new one.

**Comment by kinex** [comment] 2021-07-20 06:46
My workaround was to disable Android Keystore. There were too many mysterious issues (including also this https://github.com/google/tink/issues/413#issuecomment-707160464) so my conclusion was that it is not usable for a production app. Disabling Android Keystore should be safe enough for most apps, as documented [here](https://google.github.io/tink/javadoc/tink-android/HEAD-SNAPSHOT/com/google/crypto/tink/integration/android/AndroidKeysetManager.html).

**Comment by kyze8439690** [comment] 2021-12-12 17:48
> 1.1.0-alpha02

`androidx.security:security-crypto:1.1.0-alpha03` still has this issue

**Comment by hawklike** [comment] 2022-06-02 10:20
> > 1.1.0-alpha02
> 
> `androidx.security:security-crypto:1.1.0-alpha03` still has this issue

`androidx.security:security-crypto-ktx:1.1.0-alpha03` too

**Comment by mirjalal** [comment] 2022-08-01 14:27
any progress?

**Comment by ruslan-kuziak** [comment] 2022-11-10 11:52
`androidx.security:security-crypto:1.1.0-alpha04` has been released. I haven't tried it myself since it requires `targetSdk 33`, but I will do it as soon as I get a chance to update `targetSdk`.

There is a chance that `alpha04` fixes this.
