### ISSUE TITLE
mvn package don't generate classes

### ISSUE THREAD

**Issue by peterasik** [google/tink#245] opened 2019-08-21 09:35 UTC
With tink in version 1.2.2 or tink-awskms in version 1.3.0-rc1 in dependencies mvn don't generate classes, checked at fresh project.

Project with this dependencies attached
[test.zip](https://github.com/google/tink/files/3524607/test.zip)

**Comment by thaidn** [comment] 2019-09-17 20:05
@chuckx FYI, this may be relevant to our release process

**Comment by thaidn** [comment] 2019-12-20 08:39
Do we have a fix for this Charles?

**Comment by chuckx** [comment] 2019-12-20 17:34
Looking into this now...

**Comment by chuckx** [comment] 2019-12-20 21:55
In my troubleshooting, I found that if you specify the usage of Java 1.7 for compilation, the `mvn package` execution completes successfully. Otherwise (in my environment at least), it's defaulting to Java 1.5 and failing.

The configuration snippet within your `pom.xml` filewould look like this (using [the first approach described in this bit of the Maven documentation](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html)):
```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>
```

The second approach (configuring the plugin directly) is demonstrated within [the Java helloworld example app](https://github.com/google/tink/blob/78b908124efbb34acc4de3ae11b41112cb41adb2/examples/helloworld/java/pom.xml#L68).

Also, I'd avoid depending on different versions of Tink packages. For example, use version 1.3.0-rc3 of both `tink` and `tink-awskms`, not different versions of each.

I'll close this issue for now. However, if I haven't addressed the root cause of your issue, please reopen and provide further clarification.

**Closed by chuckx** 2019-12-20 21:55 UTC
