### ISSUE TITLE
Duplicate class jetified-tink and jetified-tink-awskms

### ISSUE THREAD

**Issue by SomonTeknoloji** [google/tink#565] opened 2021-12-24 12:41 UTC
I would like to use AWS KMS integration in my Java Android Project. 

Anyway I have just applied the sample code in JAVA-HOWTO.md but the problem was that AwsKmsClient wasn't able to resolve by Android Studio I think it was because I was using 'com.google.crypto.tink:tink-android:1.6.1' in my Gradle. 

I have seen since 1.3.0 I have to apply as a different package in my gradle so I did implement tink-awskms in gradle. I couldn't use them both so I have deleted tink-android module from the gradle and left only tink-awskms but still I cannot run my app because of some Duplicate class errors. I have tried every way actually. Protobufs, excluding modules on gradle after 3 hours of work I still have nothing.
 
 I will drop my gradle file and the errors that I'm getting during the compile time.
 
 `configurations {
        all {
            exclude group: "com.google.crypto.tink", module: "jetified-tink"
            exclude group: "com.google.crypto.tink", module: "jetified-tink-android"
        }
    } `
    
 ` implementation 'androidx.appcompat:appcompat:1.4.0' `
 `implementation 'com.google.android.material:material:1.4.0' `
  `implementation 'androidx.constraintlayout:constraintlayout:2.1.2'`
  `testImplementation 'junit:junit:4.+'`
  `androidTestImplementation 'androidx.test.ext:junit:1.1.3' `
  `androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'`
  `implementation("com.google.guava:guava:31.0.1-jre")`
  ` // Import the BoM for the Firebase platform `
  ` implementation platform('com.google.firebase:firebase-bom:29.0.3') `
  `implementation 'com.google.firebase:firebase-storage' `
   `implementation 'com.google.crypto.tink:tink-awskms:1.6.1' `
   
   
   Error that I'm getting;
`Duplicate class com.google.crypto.tink.Aead found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.KmsClient found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.KmsClients found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.config.TinkFips found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.config.TinkFips$1 found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.config.TinkFips$AlgorithmFipsCompatibility found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.config.TinkFips$AlgorithmFipsCompatibility$1 found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.config.TinkFips$AlgorithmFipsCompatibility$2 found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.config.TinkFipsDisabled found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.config.TinkFipsStatus found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.subtle.Enums found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.subtle.Enums$HashType found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.subtle.Validators found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`
`Duplicate class com.google.crypto.tink.subtle.Validators$1 found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-awskms-1.6.1 (com.google.crypto.tink:tink-awskms:1.6.1)`

**Comment by minsunp** [comment] 2022-06-27 17:41
Same issue on `tink-gcpkms:1.6.1`:
`Duplicate class com.google.crypto.tink.Aead found in modules jetified-tink-1.6.1 (com.google.crypto.tink:tink:1.6.1) and jetified-tink-gcpkms-1.6.1 (com.google.crypto.tink:tink-gcpkms:1.6.1)`

I tried removing `implementation 'com.google.crypto.tink:tink-android:1.6.1'` from gradle and excluded the duplicate class:
`implementation('com.google.crypto.tink:tink-gcpkms:1.6.1') {
    exclude group: 'com.google.crypto.tink.Aead'
  }`
but I'm getting the same error.

**Comment by morambro** [comment] 2023-02-01 10:51
Hi, I cannot reproduce the error, could you please try using `com.google.crypto.tink:tink-gcpkms:HEAD-SNAPSHOT` and see if https://github.com/google/tink/commit/a32ff51877d048c858f116de68d5ab20e63af6fe fixes this issue?

**Comment by morambro** [comment] 2023-03-08 16:57
I am going to close this issue. Please feel free to reopen it if this still remains an issue.

These changes where included in release [v.1.8.0](https://github.com/tink-crypto/tink-java/releases/tag/v1.8.0)

**Closed by morambro** 2023-03-08 16:57 UTC
