### ISSUE TITLE
Manifest is null when reading from JarInputStream

### ISSUE THREAD

**Issue by ywang-nr** [google/tink#576] opened 2022-01-25 22:13 UTC
**Help us help you**

We’d like to know more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Describe the bug:**
**Example code as below**
File input = new File(getClass().getResource("/tink-1.6.1.jar").toURI());
JarInputStream jarInputStream = new JarInputStream(new FileInputStream(input));
Manifest test = jarInputStream.getManifest()
==> test is null here

**I've tested all the versions**
1.3.0 -> working as manifest is not null
1.4.0,1.5.0,1.6.0,1.6.1 -> manifest is null for all of them

**What was the expected behavior?**

Manifest shouldn't be null

**How can we reproduce the bug?**

Follow the code example

**Do you have any debugging information?**

Follow the code example

**Provide your version information:**

-   Language: Java
-   Version: 11
-   Environment: Android Studio, JDK 11

**Is there anything else you’d like to add?**

Provide any additional context about the problem.

**Comment by chuckx** [comment] 2023-09-20 00:18
I looked into this and was mostly unable to reproduce the problem.

I say mostly because I did find an issue with the v1.7.0 jar, where the manifest file is present, but isn't an initial file within the ZIP, which it seems is an unstated requirement of JAR files (see https://bugs.openjdk.org/browse/JDK-8031748).

Here's the code I used to investigate:

```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.jar.JarInputStream;
import java.util.jar.Manifest;

final class TinkManifestInfo {

    public static void main(String[] args) throws URISyntaxException, FileNotFoundException, IOException {
        File folder = new File("./");
        File[] files = folder.listFiles();
        for (int i = 0; i < files.length; i++) {
            String name = files[i].getName();

            if (!files[i].isFile() || !name.matches(".*\\.jar$")) {
                continue;
            }

            System.out.print(name + " = ");

            JarInputStream jarInputStream = new JarInputStream(new FileInputStream(files[i]));
            Manifest manifest = jarInputStream.getManifest();

            if (manifest == null) {
                System.out.println("null manifest");
            } else {
                System.out.println(manifest.getMainAttributes().entrySet());
            }
        }
    }
}
````

I populated the directory with JAR files from releases 1.3.0 - 1.10.0:

```
$ ls -1
tink-1.10.0.jar
tink-1.3.0.jar
tink-1.4.0.jar
tink-1.5.0.jar
tink-1.6.0.jar
tink-1.6.1.jar
tink-1.7.0.jar
tink-1.8.0.jar
tink-1.9.0.jar
TinkManifest.java
```

Output from running the program:
```
$ java TinkManifest.java
tink-1.3.0.jar = [Manifest-Version=1.0, Created-By=singlejar]
tink-1.4.0.jar = [Manifest-Version=1.0, Created-By=singlejar]
tink-1.6.0.jar = [Manifest-Version=1.0, Created-By=singlejar]
tink-1.7.0.jar = null manifest
tink-1.8.0.jar = [Manifest-Version=1.0, Created-By=singlejar, Automatic-Module-Name=com.google.crypto.tink]
tink-1.9.0.jar = [Manifest-Version=1.0, Created-By=singlejar, Automatic-Module-Name=com.google.crypto.tink]
tink-1.10.0.jar = [Manifest-Version=1.0, Created-By=singlejar, Automatic-Module-Name=com.google.crypto.tink]
tink-1.6.1.jar = [Manifest-Version=1.0, Created-By=singlejar]
tink-1.5.0.jar = [Manifest-Version=1.0, Created-By=singlejar]
```

And demonstrating the ZIP layout difference (`grep` is prefixing the line number where the match was found, note the discrepancy in v1.7.0 where the manifest file is the last file in the archive for some reason):
```
$ ls *.jar | xargs -I{} sh -c "echo {}; unzip -l {} | grep -n MANIFEST"
tink-1.10.0.jar
5:       95  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.3.0.jar
5:       48  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.4.0.jar
5:       48  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.5.0.jar
5:       48  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.6.0.jar
5:       48  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.6.1.jar
5:       48  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.7.0.jar
951:       95  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.8.0.jar
5:       95  2010-01-01 00:00   META-INF/MANIFEST.MF
tink-1.9.0.jar
5:       95  2010-01-01 00:00   META-INF/MANIFEST.MF
```

Since the problem I found was a one-off that is no longer present multiple, more recent releases and I'm unable to replicate the problem you're seeing, I'm going to go ahead close this issue. Feel free to reopen if you have any follow up questions.

**Closed by chuckx** 2023-09-20 00:18 UTC
Labels: p2
