### ISSUE TITLE
Request for Hashing support

### ISSUE THREAD

**Issue by sminogue** [google/tink#425] opened 2020-09-30 17:28 UTC
It would be nice if Tink provided support for hashing passwords.

**Comment by sparkingdark** [comment] 2020-10-14 07:05
@sminogue like can you give some example other packages exist with this feature ?

**Comment by sminogue** [comment] 2020-10-14 13:06
Jasypt and bouncy castle (off the top of my head) both provide one way encryption (hashing) which can be used for storage of things like passwords.

**Comment by sparkingdark** [comment] 2020-10-14 13:40
So we can take them as reference.

**Comment by lukaspieper** [comment] 2022-11-16 18:35
Hi,

I think there is a duplicate of this at #446. But I really agree on the last sentence there:
>Including hashing could also more often make tink the single required explicit dependency for all of an application's crypto needs.

Would be amazing if Tink provides Argon2.

**Comment by juergw** [comment] 2023-01-30 13:54
I'm sorry, but we currently do not have plans to design or implement password hashing.

**Comment by BigPanda97** [comment] 2023-01-30 23:39
> I'm sorry, but we currently do not have plans to design or implement password hashing.

But why? It is a feature which has been requested many times now.

**Comment by juergw** [comment] 2023-01-31 08:26
Because we have a lot of other things planned and we only have limited resources.
But it is a reasonable feature request, so I guess we can also keep it open for now.

**Comment by tholenst** [comment] 2024-01-10 16:21
Unfortunately, there is no way we can do this at the moment -- simply due to the limits in our bandwidth at the moment. I will close this.

**Closed by tholenst** 2024-01-10 16:21 UTC
Labels: p3
