### ISSUE TITLE
Proguard Rules for Tink 1.5.0

### ISSUE THREAD

**Issue by johnnyzen** [google/tink#463] opened 2021-01-19 16:35 UTC
Hi All,

I am not sure my proguard rules are working anymore on 1.5.

Ijava.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.app/com.test.app.ui.login.LoginActivity}: java.lang.RuntimeException: java.security.GeneralSecurityException: Primitive type d.g.c.a.a not supported by key manager of type class d.g.c.a.h0.b, supported primitives: d.g.c.a.s

I am using: **com.google.crypto.tink:tink-android:1.5.0**

My proguard rules are:

# Tink
-keep class com.google.crypto.tink.proto.** { *;}
-dontwarn com.google.crypto.tink.proto.**
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite {   <fields>; }

Can anyone assist. Many thanks.

**Comment by tholenst** [comment] 2021-01-19 17:16
In principle, Tink should not require a proguard config at all. If it does for part of it (even the protos), I might actually check and see if I can fix it (thought I'm pretty overworked right now).

This message however "Primitive type d.g.c.a.a not supported by key manager of type class d.g.c.a.h0.b, supported primitives: d.g.c.a.s" suggests more that you're trying to request the wrong primitive somewhere. (I.e., you call something like GetPrimitive<Mac> where you should call GetPrimitive<Aead>). You can make proguard output the mapping and you should see what these classes map to, that might help. (Or try without proguard? Does it work then?)

**Comment by thaidn** [comment] 2021-01-20 06:23
Tink is shipped with a the following Proguard config that should work out of the box:

https://github.com/google/tink/blob/master/java_src/src/main/resources/META-INF/proguard/protobuf.pro

**Comment by johnnyzen** [comment] 2021-01-20 09:39
Hi, thanks for your support.

Yes it works without proguard. I will go back to 1.4 to see if I am being stupid and missing something.

**Comment by tholenst** [comment] 2021-01-20 09:48
Thanks Thai, I forgot we had to make this change.

I would still check the log file to see what the classes d.g.c.a.a and d.g.c.a.s are, they are obviously classes renamed by proguard.

It is possible that there's a bug in Tink there, but it doesn't have to do with protobuf, it might be rather some change to the registry.

Are you using custom Keymanagers?

**Comment by johnnyzen** [comment] 2021-01-20 09:54
Hi, thanks for the mapping log.

I have matched:

```
41:41:java.lang.Throwable tryInternalFastPathGetFailure(com.google.common.util.concurrent.internal.InternalFutureFailureAccess) -> a
com.google.crypto.tink.Aead -> d.g.c.a.a:

105:107:void validateKeyFormat(com.google.crypto.tink.proto.AesCmacKeyFormat) -> g
com.google.crypto.tink.mac.HmacKeyManager -> d.g.c.a.h0.b:

com.google.crypto.tink.Mac -> d.g.c.a.s:
    void verifyMac(byte[],byte[]) -> a
    byte[] computeMac(byte[]) -> b
```

**Comment by johnnyzen** [comment] 2021-01-20 09:59
After moving to 1.5.0 I made some changes, in which my understanding is poor (forgive me)

The two methods I changed are:

```
private fun getAEAD(prefKey: String): Aead {
        val keySetHandle = generateKeySetHandler(prefKey)
        return keySetHandle.getPrimitive(Aead::class.java)
    }

    private fun generateKeySetHandler(prefKey: String): KeysetHandle {
        val params = HmacParams.newBuilder().setHash(HashType.SHA512).setTagSize(64).build();
        val format = HmacKeyFormat.newBuilder().setParams(params).setKeySize(64).build()
        val keyTemplate = KeyTemplate.create(
            HmacKeyManager().keyType,
            format.toByteArray(),
            KeyTemplate.OutputPrefixType.TINK
        )
        val androidKeySetManager = AndroidKeysetManager.Builder()
            .withKeyTemplate(keyTemplate)
            .withSharedPref(context, prefKey, keySetFileName)
            .withMasterKeyUri(masterUri.toString())
            .build()
        return androidKeySetManager.keysetHandle
    }
```

**Comment by johnnyzen** [comment] 2021-01-20 10:07
I have added to proguard `-keep class com.google.crypto.tink.** { *; }` as a test.

Looks like I need to learn some more about what I am doing ;) Hope this is useful to someone. Looks like my issue :)

Thanks for help.

```
Primitive type com.google.crypto.tink.Aead not supported by key manager of type class com.google.crypto.tink.mac.HmacKeyManager, supported primitives: com.google.crypto.tink.Mac

Caused by: java.lang.RuntimeException: java.security.GeneralSecurityException: Primitive type com.google.crypto.tink.Aead not supported by key manager of type class com.google.crypto.tink

Caused by: java.security.GeneralSecurityException: Primitive type com.google.crypto.tink.Aead not supported by key manager of type class com.google.crypto.tink.mac.HmacKeyManager, supported primitives: com.google.crypto.tink.Mac
```

**Comment by tholenst** [comment] 2021-01-20 10:21
Yes, the issue is that you are building an HMAC key (HmacKeyFormat.newBuilder()...), but you want to use it with an AEAD. HMAC keys are made for the Mac primitive.

**Comment by thaidn** [comment] 2021-01-27 17:08
```
private fun generateKeySetHandler(prefKey: String): KeysetHandle {
        val params = HmacParams.newBuilder().setHash(HashType.SHA512).setTagSize(64).build();
        val format = HmacKeyFormat.newBuilder().setParams(params).setKeySize(64).build()
        val keyTemplate = KeyTemplate.create(
            HmacKeyManager().keyType,
            format.toByteArray(),
            KeyTemplate.OutputPrefixType.TINK
        )
        val androidKeySetManager = AndroidKeysetManager.Builder()
            .withKeyTemplate(keyTemplate)
            .withSharedPref(context, prefKey, keySetFileName)
            .withMasterKeyUri(masterUri.toString())
            .build()
        return androidKeySetManager.keysetHandle
    }
```

@johnnyzen hey there, why are you building your own key template? `HmacParams`, `HmacKeyFormat`, and everything under `com.google.crypto.tink.proto` are internal -- we don't expect users to directly depend on them.

**Comment by tholenst** [comment] 2023-01-27 12:21
I will close this -- as far as I can tell this should be fixed.

For the original issue: Tink should not require any proguard configuration. Please report it as an issue if you need any.

**Closed by tholenst** 2023-01-27 12:21 UTC
