### ISSUE TITLE
"go get" fails when specifying "latest" version as a Go module dependency

### ISSUE THREAD

**Issue by gdbelvin** [google/tink#215] opened 2019-05-23 17:07 UTC
The `go/keyset` API is not present in the latest release, which causes problems when trying to use go modules:

```
GO111MODULE=on go get github.com/google/tink/go/keyset
go: finding github.com/google/tink/go/keyset latest
go: finding github.com/google/tink/go latest
go get github.com/google/tink/go/keyset: no matching versions for query "latest"
```

**Comment by Riszin** [comment] 2019-05-26 06:00
@ #214

**Comment by Riszin** [comment] 2019-05-26 06:01
`hello world`

**Comment by thaidn** [comment] 2019-05-28 19:31
@tl0gic

**Comment by yan** [comment] 2019-06-25 04:51
Any updates?

**Comment by przydatek** [comment] 2019-06-25 10:42
Yes, we're planning to have a RC out this week.  Sorry for the delays.

**Comment by freygriff** [comment] 2019-07-02 22:05
#215

**Comment by DazWilkin** [comment] 2019-07-08 19:25
By way of follow-up, I think tink continues to need a version specifier.. this time for `/go/core/registry`:

I cloned an existing non-modules repo that uses tink and added modules, `go mod init ...`.

During `GO111MODULE=on GOPROXY=https://proxy.golang.org go get ./...` it failed:
```
cannot load github.com/google/tink/go/core/registry: cannot find module providing package github.com/google/tink/go/core/registry
```
And:
```Golang
go get github.com/google/tink/go/core/registry
go: finding github.com/google/tink/go/core/registry latest
go: finding github.com/google/tink/go/core latest
go: finding github.com/google/tink/go latest
go get github.com/google/tink/go/core/registry@latest: no matching versions for query "latest"
```
I can get both `v1.2.2` and `v1.3.0-rc1`:

```Golang
go get github.com/google/tink/go/core/registry@v1.3.0-rc1
go: finding github.com/google/tink/go/core/registry v1.3.0-rc1
go: finding github.com/google/tink/go/core v1.3.0-rc1
go: finding github.com/google/tink/go v1.3.0-rc1
go: finding github.com/google/tink v1.3.0-rc1
go: downloading github.com/google/tink v1.3.0-rc1
go: extracting github.com/google/tink v1.3.0-rc1
go: finding github.com/aws/aws-sdk-go v1.19.40
go: finding golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: finding golang.org/x/oauth2 v0.0.0-20190523182746-aaccbc9213b0
go: finding google.golang.org/api v0.5.0
go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
```

**Comment by thaidn** [comment] 2019-07-23 19:59
Thanks for the report, @DazWilkin.

@tl0gic could you please take a look?

**Comment by tl0gic** [comment] 2019-07-31 22:17
I just tested it locally on macOS 10.14.5 with go v1.12.7 and I couldn't reproduce it:

> go get github.com/google/tink/go/keyset 
go: finding github.com/golang/protobuf v1.3.1
go: finding github.com/aws/aws-sdk-go v1.19.40
go: finding golang.org/x/oauth2 v0.0.0-20190523182746-aaccbc9213b0
go: finding golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: finding google.golang.org/api v0.5.0
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding google.golang.org/appengine v1.4.0
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding cloud.google.com/go v0.34.0
go: finding github.com/golang/protobuf v1.2.0
go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
go: finding golang.org/x/tools v0.0.0-20190312170243-e65039ee4138
go: finding google.golang.org/grpc v1.19.0
go: finding google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: finding golang.org/x/sync v0.0.0-20190227155943-e225da77a7e6
go: finding go.opencensus.io v0.21.0
go: finding github.com/google/go-cmp v0.2.0
go: finding golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: finding honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: finding google.golang.org/appengine v1.1.0
go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
go: finding cloud.google.com/go v0.26.0
go: finding github.com/golang/mock v1.1.1
go: finding github.com/client9/misspell v0.3.4
go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: finding github.com/hashicorp/golang-lru v0.5.0
go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: finding google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding github.com/BurntSushi/toml v0.3.1
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding golang.org/x/tools v0.0.0-20190226205152-f727befe758c
go: finding golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding golang.org/x/exp v0.0.0-20190121172915-509febef88a4
go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: finding github.com/google/tink/go/keyset latest
go: downloading github.com/golang/protobuf v1.3.1
go: extracting github.com/golang/protobuf v1.3.1

> go get github.com/google/tink/go/core/registry
go: finding github.com/google/tink/go/core/registry latest


It appears to be able to resolve everything. Can you retry with tink @ master ?

**Comment by gdbelvin** [comment] 2019-08-01 08:11
This issue appears to still be present

```
go version go1.12.7 darwin/amd64
GO111MODULE=on go get github.com/google/tink/go/keyset
go: finding github.com/google/tink/go/keyset latest
go: finding github.com/google/tink/go latest
go: finding github.com/google/tink v1.2.2
go: downloading github.com/google/tink v1.2.2
go: extracting github.com/google/tink v1.2.2
go get github.com/google/tink/go/keyset: no matching versions for query "latest"
```

**Comment by freygriff** [comment] 2019-08-01 12:58
Freya Griffin

----- Reply message -----

**Comment by freygriff** [comment] 2019-08-01 13:14
Freya Griffin

----- Reply message -----
From: "ms.freyanabours97@gmail.com" <ms.freyanabours97@gmail.com>
To: "google/tink" <reply@reply.github.com>, "google/tink" <tink@noreply.github.com>
Cc: "Comment" <comment@noreply.github.com>
Subject: [google/tink] Create new release (#215)
Date: Thu, Aug 1, 2019 7:58 AM

Freya Griffin

----- Reply message -----

**Comment by tl0gic** [comment] 2019-08-01 17:33
The way we setup go modules is by having the entire repo as one big module. There is a go.mod file in https://github.com/google/tink/blob/master/go.mod.

What happens if you try:
GO111MODULE=on go get github.com/google/tink ?

**Comment by tl0gic** [comment] 2019-08-01 18:13
So the issue is that when go looks up the "latest" version it gets back 1.2.2 which doesn't have go module support.

What you need to do it either explicitly request 1.3.0-rc1 or update your go.mod and replace 1.2.2 with 1.3.0-rc1 as described here: https://github.com/google/tink/issues/234#issuecomment-517351561

This will be fixed once we release 1.3.0 final. let me know if that works for you or if you run into other issues.

**Comment by DazWilkin** [comment] 2019-08-01 19:03
Yes, this is the issue but it continues to not work for me:

```Golang
package main

import (
    "fmt"
    "github.com/google/tink"
)

func main() {
    fmt.Println("Hello Freddie!")
}
```
go.mod:
```
module main

go 1.12

require github.com/google/tink v1.3.0-rc1
```
and:
```bash
GO111MODULE=on go build ./...
build main: cannot load github.com/google/tink: cannot find module providing package github.com/google/tink
```
with:
```bash
go list -f "{{.Dir}}" -m github.com/google/tink
/usr/local/google/home/dazwilkin/go/pkg/mod/github.com/google/tink@v1.3.0-rc1
```

**Comment by tl0gic** [comment] 2019-08-01 19:09
This is what I have and works:

hello.go:
```
package main

import (
  "fmt"
  "log"

  "github.com/google/tink/go/aead"
  "github.com/google/tink/go/keyset"
)

func main() {

  kh, err := keyset.NewHandle(aead.AES256GCMKeyTemplate())
  if err != nil {
    log.Fatal(err)
  }

  a, err := aead.New(kh)
  if err != nil {
    log.Fatal(err)
  }

  ct, err := a.Encrypt([]byte("this data needs to be encrypted"), []byte("associated data"))
  if err != nil {
    log.Fatal(err)
  }

  pt, err := a.Decrypt(ct, []byte("associated data"))
  if err != nil {
    log.Fatal(err)
  }

  fmt.Printf("Cipher text: %s\nPlain text: %s\n", ct, pt)

}
```

go.mod (ignore the module name):
```
module github.com/tl0gic/hello

go 1.12

require (
	github.com/golang/protobuf v1.3.2 // indirect
	github.com/google/tink v1.3.0-rc1
)
```

go build

**Comment by DazWilkin** [comment] 2019-08-01 19:41
My bad.... "github.com/google/tink/**go**".

Yes, that now works.

**Comment by thaidn** [comment] 2019-09-17 20:09
This looks like this can be closed now. Please reopen if you need additional help.

**Closed by thaidn** 2019-09-17 20:09 UTC
