### ISSUE TITLE
Cannot install it with googleapis-common-protos and other related libs in python

### ISSUE THREAD

**Issue by ankit-sapkota555** [google/tink#695] opened 2023-05-31 07:14 UTC
When trying to install it with googleapis-common-protos the following issue seems to be present.

Tink requires protobuf version 3.20.1 but it is not supported by the googleapis-common-protos and hence dependency resolving fails.

-   Language:  Python
-   Version: 3.7
-   Environment: (Ubuntu )

I am using poetry to manage deps

**Comment by qTipTip** [comment] 2023-06-02 15:22
Hey! First of all, thanks for developing Tink!

I am having the same issue: 

```
Because no versions of tink match >1.7.0,<2.0.0
 and tink (1.7.0) depends on protobuf (3.20.1), tink (>=1.7.0,<2.0.0) requires protobuf (3.20.1).
And because google-cloud-secret-manager (2.16.1) depends on protobuf (>=3.19.5,<3.20.0 || >3.20.0,<3.20.1 || >3.20.1,<4.21.0 || >4.21.0,<4.21.1 || >4.21.1,<4.21.2 || >4.21.2,<4.21.3 || >4.21.3,<4.21.4 || >4.21.4,<4.21.5 || >4.21.5,<5.0.0dev)
 and no versions of google-cloud-secret-manager match >2.16.1,<3.0.0, tink (>=1.7.0,<2.0.0) is incompatible with google-cloud-secret-manager (>=2.16.1,<3.0.0).
So, because ... depends on both google-cloud-secret-manager (^2.16.1) and tink (^1.7.0), version solving failed.
```

**Comment by tholenst** [comment] 2023-06-05 11:18
It would be good if we followed https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#install-requires : 

"It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades."

**Comment by dega2** [comment] 2023-06-22 15:30
@morambro thank you for your reply. 
I have setup a fresh Ubuntu 20.04, Python 3.10 and the coresponding Pip. 
I used the Ubuntu APT package protobuf-compiler. I checked the version with: protoc --version    output: libprotoc 23.0
I followed the Bazel installation procedure from the Bazel Git.
The tink package was build with: pip wheel .

**Comment by morambro** [comment] 2023-06-22 15:35
I think the issue is the version of protoc; note that Tink Python at HEAD requires [>=4.21.9](https://github.com/google/tink/blob/master/python/requirements.in#L2). You may try with a more recent version (e.g., see [here](https://github.com/google/tink/blob/master/python/tools/distribution/build_linux_binary_wheels.sh#L51)).

**Comment by morambro** [comment] 2023-08-28 11:03
1.8.0 is out ([notes](https://github.com/tink-crypto/tink-py/releases/tag/v1.8.0), [pypi](https://pypi.org/project/tink/1.8.0/))., which includes a fix for this issue.

**Closed by morambro** 2023-08-28 11:03 UTC
Labels: bug, p2
