### ISSUE TITLE
Tink 1.7.0 to CocoaPods

### ISSUE THREAD

**Issue by hohyeonmoon** [google/tink#666] opened 2023-01-19 08:52 UTC
It seems that the release of [Tink 1.7.0](https://github.com/google/tink/releases/tag/v1.7.0) is in Pending for Cocoapods publication. Would it be possible to get this published? It would be awesome for us to use this in Apple Silicon at Native environment.

**Comment by chuckx** [comment] 2023-05-20 05:47
Duplicate of #641

**Closed by chuckx** 2023-05-20 05:47 UTC
Labels: p2
